- createlinks
- root/etc/e-smith/templates/etc/httpd/conf.d/zz_mattermost.conf/10base
> httpd conf: add TLS policy

- root/etc/e-smith/templates/etc/httpd/conf.d/zz_mattermost.conf/10base
> httpd conf: do not replace default virtualhost

- root/etc/e-smith/templates/etc/httpd/conf.d/zz_mattermost.conf/10base
No need to duplicate the global settings logic for SSL
NethServer/dev#5509
> Inherit SSL settings from global server scope

- nethserver-mattermost.spec
> Upgrade to 4.10.1

- nethserver-mattermost.spec
Update for security fixes
NethServer/dev#5702
> Upgrade to upstream 5.7.0

- nethserver-mattermost.spec
Update for security fixes
NethServer/dev#5734
> Upgrade to upstream 5.9.0

- nethserver-mattermost.spec
> Update to upstream 5.12.2

- nethserver-mattermost.json
- nethserver-mattermost.spec
> Automatically update cockpit app release

- nethserver-mattermost.spec
> Update to upstream 5.14.2

- nethserver-mattermost.spec
- root/etc/sudoers.d/50_nsapi_nethserver_mattermost
https://github.com/NethServer/dev/issues/5805
> Cockpit Mattermost config for sudoers delegation

- nethserver-mattermost.spec
> Update to 5.15.0

- root/usr/sbin/mattermost-bulk-user-create
- platform binary has been deprecated
- new password policy requires a minimum length of 10 chars
NethServer/dev#5851
> bulk: use mattermost binary

- nethserver-mattermost.spec
> Update to 5.17.1

- root/opt/puppetlabs/puppet/lib/ruby/2.1.0/facter/mattermost.rb
Count users, teams and posts
NethServer/dev#5979
> Add fact for inventory

- ui/index.html
- ui/views/dashboard.html
Updated dashboard title and app name.
Refer to https://github.com/NethServer/dev/issues/6004
> ui. update dashboard title and app name

- createlinks
https://github.com/NethServer/dev/issues/6170
see for explanation https://github.com/NethServer/dev/issues/6170#issuecomment-632118547
> Removed unused tls-policy-save

- api/read
- ui/i18n/language.json
- ui/js/app.js
- ui/views/dashboard.html
Include disk usage of database and `/var/lib/nethserver/mattermost` directory in dashboard page
NethServer/dev#6191
> Database and data disk usage in dashboard page

- ui/js/app.js
- ui/views/dashboard.html
Make statistics numbers easily readable.
E.g: display **14 K connections** instead of **14536 connections**
NethServer/dev#6206
> Display numbers in a human readable form

- nethserver-mattermost.spec
> Upgrade to latest 5.25 release

- root/etc/e-smith/events/actions/nethserver-mattermost-conf-json
Mattermost defaults are not valid for NethServer installations
NethServer/dev#6273
> conf: fix SMTP configuration

- root/etc/e-smith/events/actions/nethserver-mattermost-conf-json
Prevent config file corruption and fix existing corrupted files.
NethServer/dev#6407
> conf: prevent JSON corruption

- root/etc/e-smith/events/actions/nethserver-mattermost-conf-json
- Fix firstRun condition
- Set new push server default: https://docs.mattermost.com/overview/faq.html#are-mobile-push-notifications-free
NethServer/dev#6489
> Fix push notification server

- createlinks
- root/etc/e-smith/events/actions/nethserver-mattermost-fix-rsync-perms
> rsync: fix permissions and ownership issues

- nethserver-mattermost.spec
Update to latest release
NethServer/dev#6731
> Update to 7.7.1

- nethserver-mattermost.spec
> Update to 8.0.0
